qi_client:
  base_url: "http://localhost"
  api_key: "AUTHORIZATION_KEY"
  private_key: "BASE_64_API_KEY"
  private_key_password: "PASSWORD"
  provider_pub_key: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHYk1CQUdCeXFHU000OUFnRUdCU3VCQkFBakE0R0dBQVFBcnBNU2dJTHFQS2N0ZXdUdVRBdW55Q3JzMjB4ZwpEd2FKZzRSQStBTmp0cmoxRVVnUVVvMjhKWXEwUHJxdGlDa21NcFU5NTloellLSCtFT2RpSG9ST3pZb0JPYnNhCnhMN2hFVDFkU21SYXlrUytWWkkvNU5OS1NERmJENGNXbGVrZUFGcEpUeitsUDV1SzlISTI2ejk5bXVlY3hwRjMKRHNYaURCa1NGcjJ5cVgxQWFCZz0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t"
